### ISSUE TITLE
cat icon breaks when using 4:3, and shifts slightly when using any other resolution other than 1440p

### ISSUE THREAD

**Issue by SimpleBrian** [SimpleBrian/jazztronauts#1]
probably thanks to my crazy spaghet code but uh yeah.
https://github.com/SimpleBrian/jazztronauts/blob/ui-changes/gamemodes/jazztronauts/gamemode/ui/dialog/cl_styling.lua

**Comment by SimpleBrian** [comment]
added checks for 16:9, 16:10 and 4:3, but couldn't add check for resolutions 720p and below because it caused shit to break???

**Comment by RDBomber** [comment]
i added scuffed code and did nothing i had no idea on where to start lmao
glad to see this working though

**Comment by SimpleBrian** [comment]
w
